import { RedComponent } from '@chin2km/ui-components';
import React, { FC } from 'react';

export const RedPage: FC = () => {
  return (
    <>
      <RedComponent />
      <h2>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in nisl enim. Suspendisse potenti. Sed ut finibus neque. Sed interdum eleifend elementum. Mauris eget erat ut enim iaculis maximus a at ante. Aenean consequat dictum elit, ac dapibus urna porttitor vel. Nam non risus quis augue pellentesque congue. Fusce tempus mattis venenatis. Praesent sed facilisis magna.
        Donec dignissim tincidunt vestibulum. Aenean aliquam, turpis interdum tempor rutrum, magna lectus imperdiet odio, sed pharetra erat sapien vitae leo. Morbi convallis turpis et ligula mollis sollicitudin. Donec non scelerisque arcu. Curabitur vestibulum sapien et tellus sodales, dapibus mattis justo aliquet. Donec ullamcorper et elit quis cursus. Donec vitae luctus orci, ut pretium enim. Morbi varius imperdiet turpis vitae faucibus. Donec condimentum sollicitudin dolor nec auctor. Aenean elementum dapibus eros, sit amet lobortis ligula lobortis at. Ut lorem quam, vestibulum ac ligula eu, lacinia suscipit justo. Aenean sagittis dui id facilisis commodo. Duis et tortor cursus, vestibulum lectus ac, tristique sapien. Curabitur id lectus et ante tristique rhoncus et a urna.
        Sed consequat, risus ut lobortis tempus, dolor purus convallis dui, eu auctor enim ligula id metus. In erat odio, aliquam sed volutpat ac, fermentum in ex. In diam justo, condimentum hendrerit orci ac, pellentesque dictum nisl. Integer egestas ante sed eros vestibulum, et finibus libero molestie. Phasellus dignissim odio sed leo venenatis, id aliquet ex molestie. Nullam faucibus, dui at ultrices fringilla, massa lorem cursus tortor, vel tincidunt augue magna vel dui. Aenean ut fringilla mi. Proin at imperdiet sapien. Morbi vitae ultrices dui. Suspendisse potenti. Pellentesque at elementum sem. Praesent fringilla cursus nisl sed accumsan.
        Fusce et augue convallis magna maximus dignissim eu at odio. Donec semper risus auctor, scelerisque libero eu, hendrerit neque. Nulla bibendum dui quis sem ultrices, at sollicitudin sem hendrerit. Nunc eget sapien non ex vehicula iaculis. Nunc eleifend malesuada vehicula. Sed sed mattis nibh. Quisque euismod dignissim neque, sollicitudin cursus neque maximus suscipit. Duis id porta metus. Nullam ut volutpat lacus, nec dignissim nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam fringilla justo at sagittis feugiat. Nulla suscipit, sem at cursus facilisis, felis est accumsan nulla, quis scelerisque magna turpis nec velit. Donec pharetra vitae erat a scelerisque. Donec vel purus sapien.
        Integer bibendum non ante convallis sollicitudin. Etiam vel pharetra lacus, sit amet auctor sapien. Pellentesque at mollis elit. Proin sodales justo nec cursus interdum. Praesent suscipit libero sit amet dui tincidunt varius. Integer eget commodo ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras molestie elementum mauris, quis finibus libero commodo sed. Nam feugiat velit quis dui interdum aliquam. Nunc id vestibulum mi, auctor venenatis nibh. Aliquam blandit nulla ac lacus posuere, nec laoreet dui consectetur. Nam et feugiat lorem. Quisque eget nulla quis mauris porta maximus vitae ut turpis. Nam dapibus hendrerit tincidunt. Aenean pretium magna efficitur purus sollicitudin, quis vestibulum sem pulvinar.
        Vestibulum eget neque imperdiet, ullamcorper mi in, congue tellus. Pellentesque facilisis augue eget sem facilisis vestibulum. Fusce leo augue, finibus id mi sed, feugiat sagittis nulla. Vestibulum euismod molestie tortor, vel elementum sapien commodo sed. Vestibulum eget diam nulla. Vivamus sit amet varius libero, quis hendrerit nisi. Praesent a odio eget dui molestie posuere. Ut eleifend, massa aliquet finibus sollicitudin, orci felis faucibus neque, quis scelerisque neque eros quis leo. Nunc euismod elementum erat eget volutpat. Maecenas velit velit, tristique sed nibh vehicula, condimentum aliquam leo. Mauris eleifend volutpat libero, ut aliquam massa sodales non. Pellentesque cursus lacus ac risus egestas tincidunt. In et augue nec purus euismod suscipit. Nam gravida dictum lacus, interdum gravida ante. Nam accumsan at nisl et varius. Nulla facilisis, leo nec tempor sagittis, purus justo ultricies lorem, in eleifend orci felis et mi.
        Vivamus fringilla, enim sed pharetra condimentum, magna lorem blandit dolor, ac scelerisque tellus nisi ut nibh. Proin gravida dictum nunc. Maecenas molestie, massa posuere condimentum semper, libero eros porta augue, quis auctor mauris risus eget erat. Cras et nisi elementum, hendrerit est in, rutrum odio. Vestibulum id risus at ipsum viverra sodales. Quisque tempor, tellus sed consequat rutrum, nulla erat rutrum nunc, non ultrices nunc purus sodales dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis interdum viverra ligula vitae lacinia. Nullam vestibulum mauris ac vestibulum gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse fermentum dolor massa, a imperdiet felis scelerisque a. Aenean purus ipsum, tincidunt ut congue quis, iaculis in orci. Quisque sit amet leo id massa convallis commodo. Integer non est vehicula, auctor odio pulvinar, auctor lacus. Curabitur egestas mauris a enim mattis varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
        Cras molestie sem sit amet metus vulputate ullamcorper. Vivamus sapien augue, lobortis vitae erat sit amet, tempus tempus eros. Pellentesque sit amet orci eu magna fringilla fringilla sed ut felis. Etiam vitae mauris dignissim, consequat libero at, tincidunt massa. Praesent porttitor, dui quis consequat vestibulum, metus neque varius magna, ut iaculis nunc orci id mi. Nam cursus erat dolor, eget porttitor leo consequat et. Aenean ac dolor elit. Integer tincidunt placerat nibh non pharetra. Etiam non vehicula erat. Quisque egestas placerat consectetur. Aenean ut neque ac lacus aliquet congue ut pharetra mauris. Duis elit ex, interdum rutrum est ac, facilisis hendrerit est. Integer eu suscipit dolor. Fusce eu nulla eu diam rutrum tincidunt. Donec feugiat ante eget felis rutrum, vitae ullamcorper nunc rutrum. Fusce efficitur augue elit, at sagittis velit tincidunt in.
        Nunc felis orci, sagittis ac ex ac, ornare volutpat est. Donec sit amet odio vitae lectus dapibus luctus. Morbi arcu turpis, efficitur vel varius vitae, interdum quis erat. Nam placerat tincidunt consectetur. Proin aliquam quis lorem eu consequat. Sed libero sem, maximus id risus et, fermentum finibus nibh. Donec convallis risus eget purus condimentum hendrerit a in lacus. Suspendisse ut justo id ex pellentesque tincidunt. Sed a nibh quis purus condimentum maximus sed vel tortor. Sed luctus iaculis ex, at vehicula metus faucibus elementum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tempor, sem congue aliquam euismod, risus nunc pellentesque dolor, quis placerat arcu tellus sed urna. Suspendisse malesuada sapien ac tincidunt gravida. Etiam rhoncus tincidunt venenatis.
        Suspendisse vel hendrerit orci, eu pretium nulla. Sed auctor, velit eget commodo vehicula, quam metus lobortis velit, non ultrices justo lorem imperdiet ligula. Curabitur non erat accumsan ante viverra ullamcorper eget blandit diam. Maecenas aliquam faucibus commodo. Nam at lorem turpis. Integer dapibus, dui sed porttitor elementum, justo neque porttitor metus, ac fringilla sapien mauris non erat. Aenean id pulvinar justo. Nunc turpis orci, aliquam sit amet orci ut, semper imperdiet libero. Mauris porta augue massa, ut vehicula dui laoreet sed.
        Phasellus vel mattis ipsum. Etiam nec nisi auctor, luctus dui quis, vestibulum leo. Nullam vitae maximus ex, interdum blandit lorem. Donec in mauris massa. Mauris a tortor ac lectus accumsan facilisis eu vel quam. Aliquam maximus pellentesque ipsum, in euismod sem vehicula ac. Nunc aliquam bibendum tempor. Donec vestibulum diam et dolor cursus euismod non et est. Mauris feugiat pellentesque tincidunt.
        Maecenas ante turpis, fermentum sit amet massa eget, finibus cursus augue. Praesent egestas metus vitae nunc efficitur egestas. In lacinia mi placerat tellus dignissim, eget mollis erat lobortis. Sed ac aliquam neque. Vivamus ut faucibus velit, quis rhoncus odio. Maecenas id molestie leo. Sed et pulvinar neque, ac faucibus ex. Vestibulum dapibus blandit nulla, vitae ornare risus fermentum vitae. Duis finibus varius quam, et rutrum tortor tincidunt vitae. Nullam volutpat, elit a fringilla finibus, dolor nisl ultrices mi, sed ullamcorper ipsum est sed tellus.
        In faucibus suscipit nunc non consequat. Nulla sit amet porta dolor. Nulla eget felis quis nunc dictum sagittis eu ut libero. Praesent dapibus diam non auctor lobortis. Nunc sed eros nec lacus dictum imperdiet. Donec pharetra sagittis nisi, ut tincidunt magna egestas et. Mauris sem orci, pulvinar at convallis eget, luctus eu ipsum. Proin cursus libero at justo convallis maximus. Mauris sit amet sapien hendrerit quam elementum feugiat. Nullam ac enim ac lacus facilisis maximus ut eu libero. Aliquam consectetur erat vitae aliquet posuere. Proin mattis porttitor lorem fringilla accumsan.
        Aenean ultrices faucibus quam, in tristique augue tincidunt sed. Aliquam id felis nisi. Fusce turpis nisl, tincidunt bibendum mollis vel, placerat eget libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum egestas metus orci, vitae mattis orci congue id. Fusce non convallis est, ornare condimentum felis. Vivamus non massa faucibus, dignissim nunc ut, luctus ex. Fusce fringilla leo pretium ligula porttitor, id vehicula lectus volutpat.
        Sed cursus quam id metus aliquet tempor. Donec at massa non nunc ultrices facilisis sed non felis. Phasellus ligula massa, hendrerit ac ex vitae, feugiat tincidunt sem. Nam a tincidunt ligula. Phasellus congue ligula at velit feugiat, sed venenatis nisl molestie. Sed congue ipsum ultricies augue sollicitudin, ut molestie nibh aliquam. Proin sed felis arcu.
        Morbi gravida est quis nunc rhoncus, nec faucibus orci convallis. Praesent luctus pulvinar nulla vitae feugiat. Sed iaculis ac diam quis laoreet. Nulla pellentesque sit amet leo quis vulputate. In posuere ac nulla in volutpat. Morbi pretium nec nibh nec venenatis. In lobortis ipsum quis massa venenatis molestie. Praesent dapibus tellus vel sapien auctor bibendum. Vestibulum ullamcorper non odio eget blandit.
        Aenean condimentum, risus at pretium accumsan, neque ante luctus leo, quis tincidunt sem enim id libero. Pellentesque condimentum leo at tincidunt eleifend. Integer sagittis malesuada ante, vitae bibendum sapien sodales tristique. Donec vehicula porttitor ante quis euismod. Aliquam erat volutpat. Vestibulum molestie ex est, ut efficitur leo lobortis id. Phasellus eget iaculis mi. Mauris euismod quam vel tellus sagittis, ut vestibulum nibh volutpat. Donec ut magna convallis turpis tempor lobortis. Vivamus a eleifend lacus. Mauris congue mattis dolor quis cursus. Integer sed dapibus ipsum, sed lobortis nisl. Maecenas sit amet dui non dui auctor accumsan.
        Nulla consectetur dolor ut tellus consectetur, ut dictum arcu ornare. Nunc aliquet laoreet ex id sagittis. Fusce ultricies rhoncus velit, vel sodales lacus imperdiet sed. Nulla sit amet odio ultrices nisl pharetra fringilla ut ac arcu. Nunc non hendrerit lorem. Aliquam tincidunt cursus mauris quis fringilla. Donec non sapien eros. Pellentesque ut rhoncus sem. Curabitur pharetra ligula libero, ac ultricies tellus egestas id.
        Phasellus eget aliquam nunc. Integer eu arcu facilisis, eleifend elit quis, elementum felis. Vivamus vitae aliquam orci. Vivamus volutpat egestas pretium. Integer sollicitudin, arcu id malesuada mattis, elit est ultrices felis, et luctus nibh nisi id ipsum. Maecenas non faucibus enim. Nulla id lorem ante. Maecenas tempus felis vel suscipit commodo.
        Quisque viverra est elit, id ornare magna placerat et. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus orci nec felis malesuada, vel auctor ex tincidunt. Vivamus aliquet tempor diam non fringilla. Vivamus lacinia libero ante, vitae sollicitudin quam scelerisque iaculis. Nulla hendrerit consequat justo in vehicula. Praesent at nisi vulputate, auctor nisi a, gravida massa. Donec aliquet dictum sodales. Proin fermentum nisl ac enim pharetra, in commodo lectus vehicula. Vestibulum nec tortor ex. Sed vel ligula nunc. Integer tincidunt, augue rhoncus semper pulvinar, nulla sem rutrum sem, ac volutpat ipsum mi ac metus. Duis dignissim, magna id viverra feugiat, arcu dolor efficitur augue, eget fermentum eros enim et purus. Cras porta consectetur tortor, vitae rhoncus augue lacinia eu.
      </h2>
    </>
  );
};
